/** Loading canonical building data from public/data (generated by scripts/bundle-data.mts). */
import { Building, Level } from "@wf/schema";
import { type RouteGraph, buildGraph } from "@wf/routing";

export interface BuildingData {
  building: Building;
  levels: Level[];
  graph: RouteGraph;
}

async function json(url: string): Promise<unknown> {
  const res = await fetch(url, { cache: "force-cache" });
  if (!res.ok) throw new Error(`could not load ${url} (${res.status})`);
  return res.json();
}

export async function loadBuilding(id: string): Promise<BuildingData> {
  const building = Building.parse(await json(`/data/${id}/building.json`));
  const levels = await Promise.all(building.levels.map(async (l) => Level.parse(await json(`/data/${id}/levels/${l.id}.json`))));
  // Bottom to top, so level pickers and the exploded view share one order.
  levels.sort((a, b) => a.sortIndex - b.sortIndex);
  return { building, levels, graph: buildGraph(building, levels) };
}

export async function listBuildings(): Promise<string[]> {
  const index = (await json("/data/index.json")) as { buildings?: string[] };
  return index.buildings ?? [];
}
